config/routes.rb
RecordsApp::Application.routes.draw do
  get "pages/home"

  match '/artist',        :to => 'pages#artist'
  match '/tour',          :to => 'pages#tour'
  match '/street_team',   :to => 'pages#street_team'
  match '/forum',         :to => 'pages#forum'
  match '/contact',       :to => 'pages#contact'

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def artist
    @title = "Artists"
  end

  def tour
    @title = "Tour"
  end

  def street_team
    @title = "Street Team"
  end

  def forum
    @title = "Forum"
  end

  def contact
    @title = "Contact"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    base_title = "SuperPosition Records"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav>
  <div id = "top_nav">
    <%= link_to "Home", root_path, :class => "top_nav" %>
    <%= link_to "Artists", artist_path, :class => "top_nav" %>
    <%= link_to "Tour", tour_path, :class => "top_nav" %>
    <%= link_to "Street Team", street_team_path, :class => "top_nav" %>
    <%= link_to "Forum", forum_path, :class => "top_nav" %>
    <%= link_to "Contact", contact_path, :class => "top_nav" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= title %></title>
    <link rel="SHORTCUT ICON" href="/images/favicon.ico" type="image/x-icon">
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag 'jquery', 'application' %>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  </head>
  <body>


<nav>&nbsp</nav>

    <span id="superposition">SuperPosition</span><span id="pronounce">(soo-per-puh-zish-uhn)</span>
    <div id="definition"><b>N.</b> The combination of two or more physical states, such as waves, to form a new physical state in accordance with this principle.</div>



    <%= yield %>


  </body>
</html>

app/views/pages/artist.html.erb
<h1>Pages#artist</h1>
<p>Find me in app/views/pages/artist.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#test</h1>
<p>Find me in app/views/pages/tour.html.erb</p>

app/views/pages/forum.html.erb
<h1>Pages#forum</h1>
<p>Find me in app/views/pages/forum.html.erb</p>

app/views/pages/home.html.erb
<div id="main_home">
<div id="holder">
  <div id="slider">
      <div class="slide" id="slide_0"><h1>News</h1><b>June 21, 2011</b><br /><div class="slide_text">After the success of recording artist AJ Barry's CD release party we've decided to continue with this project by launching this website.  AJ will be re-release his "Chakra" album under LoveAssault. This is still the beta version of the website so keep checking back for more updates!</div> </div>
      <div class="slide" id="slide_1"><h1>Current Releases</h1><%= image_tag('chakra.jpg') %><br /><b>"The Chakras"</b> by LoveAssault</div>
      <div class="slide" id="slide_2"><h1>Coming Soon</h1><%= image_tag ('heart.jpg') %><br /><b>Rules of Attraction</b> by LoveAssault</div>
      <div class="slide" id="slide_3"><h1>About Us</h1><div class="slide_text_3">The term 'superposition' is used in quantum mechanics to describe partials when they are in wave form. The days of thinking  atoms are little balls orbiting as planets are over and so are the days of thing record labels as big money making machine. Our focus is on the talents with in every artist rather than if they have a marketable image. We also see the new trend of the DIY (Do It Yourself) movement which always artist to become more creative and in charge of their own destiny. SuperPosition Records is a label by artists for artists because as soon as people who are not in this business for the love music will quickly loose site of the true power behind music. This project is very new and we that you fallow us as we grow and evolve. </div></div>
  </div>
</div>
<div id="home_nav">
  <a id="news" class="home_link" href="#">News</a><br />
  <a id="current" class="home_link" href="#">Current</a><br />
  <a id="soon" class="home_link" href="#">Coming Soon</a><br />
  <a id="us" class="home_link" href="#">About Us</a>
</div>
</div>

app/views/pages/street_team.html.erb
<h1>Pages#street_team</h1>
<p>Find me in app/views/pages/street_team.html.erb</p>

app/views/pages/tour.html.erb
<h1>Pages#tour</h1>
<p>Find me in app/views/pages/tour.html.erb</p>